const fs = require('fs');
const path = 'db.json';

const db = JSON.parse(fs.readFileSync(path, 'utf8'));

const allAmbos = [
  "ADOLESCENCIA", "ALERGIA E INMUNOLOGÍA", "ANATOMÍA PATOLÓGICA", "ANATOMÍA PATOLÓGICA PEDIÁTRICA",
  "ANESTESIOLOGÍA", "CARDIOLOGÍA", "CARDIOLOGÍA INFANTIL", "CIRUGÍA AMBULATORIA", "CIRUGÍA CARDIOVASCULAR",
  "CIRUGÍA CARDIOVASCULAR PEDIÁTRICA", "CIRUGÍA DE CABEZA Y CUELLO", "CIRUGÍA DE TÓRAX", "CIRUGÍA GENERAL",
  "CIRUGÍA INFANTIL (CIRUG. PEDIÁTRICA)", "CIRUGÍA PLÁSTICA Y REPARADORA", "CIRUGÍA PLÁSTICA/REPARAD (POSBÁSICA)",
  "CIRUGÍA VASCULAR PERIFÉRICA", "CIRUGÍA/TRAUMBUCO-MAXILO-FACIAL", "CLÍNICA MÉDICA", "COLOPROCTOLOGÍA",
  "DERMATOLOGÍA", "DERMATOLOGÍA PEDIÁTRICA", "EMERGENTOLOGÍA", "ENDOCRINOLOGÍA", "ENDOCRINOLOGÍA INFANTIL",
  "ENFERMERÍA", "FARMACOLOGÍA CLÍNICA", "FERTILIZACIÓN ASISTIDA", "FISIATRÍA (MEDICINA FÍSICA/REHABILITACIÓN)",
  "FONOAUDIOLOGÍA", "GASTROENTEROLOGÍA", "GASTROENTEROLOGÍA INFANTIL", "GENÉTICA MÉDICA", "GERIATRÍA",
  "GINECOLOGÍA", "GUARDIA", "HEMATOLOGÍA", "HEMATOLOGÍA INFANTIL", "HOSPITAL DE DIA", "INFECTOLOGÍA",
  "INFECTOLOGÍA INFANTIL", "INMUNIZACIONES", "INMUNOLOGÍA PEDIÁTRICA", "INTERDISCIPLINARIA EDUCACIÓN PARA LA SALUD",
  "INTERDISCIPLINARIA EN CUIDADOS PALIATIVOS", "INTERDISCIPLINARIA EN GERONTOLOGÍA", "INTERNACIÓN DOMICILIARIA",
  "KINESIOLOGÍA", "KINESIOLOGÍA PEDIATRÍA Y NEONATOLOGÍA", "MASTOLOGÍA", "MEDICINA DEL DEPORTE",
  "MEDICINA DEL TRABAJO", "MEDICINA GENERAL/MEDICINA DE FAMILIA", "MEDICINA LEGAL", "MEDICINA NUCLEAR",
  "MUSICOTERAPIA", "NEFROLOGÍA", "NEFROLOGÍA INFANTIL", "NEONATOLOGÍA", "NEUMONOLOGÍA", "NEUMONOLOGÍA INFANTIL",
  "NEUROCIRUGÍA", "NEUROLOGÍA", "NEUROLOGÍA INFANTIL", "NUTRICIÓN", "NUTRICIÓN INFANTIL", "NUTRICIONISTA-DIETISTA",
  "OBSTETRICIA", "ODONTOLOGÍA", "ODONTOPEDIATRÍA", "OFTALMOLOGÍA", "ONCOLOGÍA", "ONCOLOGÍA INFANTIL",
  "ORTOPEDIA Y TRAUMATOLOGÍA", "ORTOPEDIA Y TRAUMATOLOGÍA INFANTIL", "OTORRINOLARINGOLOGÍA",
  "OTORRINOLARINGOLOGÍA PEDIÁTRICA", "OTRAS PRESTACIONES", "PEDIATRÍA", "PSICOLOGÍA",
  "PSICOLOGÍA CLÍNICA INFANTO-JUVENIL", "PSICOPEDAGOGÍA", "PSIQUIATRÍA", "PSIQUIATRÍA INFANTO-JUVENIL",
  "RADIOTERAPIA O TERAPIA RADIANTE", "REUMATOLOGÍA", "REUMATOLOGÍA INFANTIL", "TERAPIA INTENSIVA",
  "TERAPIA INTENSIVA INFANTIL", "TERAPIA OCUPACIONAL", "TOCOGINECOLOGÍA", "TOXICOLOGÍA", "TRASLADOS SANITARIOS",
  "UROLOGÍA", "DIAGNÓSTICO X IMÁGENES", "DIÁLISIS", "FARMACIA", "HEMODINAMIA", "HEMOTERAPIA",
  "LABORATORIO ANÁLISIS CLÍNICOS", "UNIDAD DE TERAPIA INTENSIVA", "UNIDAD CORONARIA",
  "UNIDAD DE CUIDADOS INTERMEDIOS", "INTERNACIÓN CRÓNICA", "UNIDAD DE TERAPIA INTENSIVA NEONATAL",
  "UNIDAD DE TERAPIA INTENSIVA PEDIÁTRICA", "SALA DE PROCEDIMIENTO", "SALA DE PARTO",
  "SALA DE ENDOSCOPÍA", "QUIRÓFANO", "QUIRÓFANO PARA HEMODINAMIA", "INTERNACIÓN GENERAL",
  "TERAPIA INTENSIVA PEDIÁTRICA", "INTERNACIÓN PROLONGADA", "TERAPIA INTENSIVA ADULTOS",
  "PEDIATRÍA", "UNIDAD CORONARIA", "NEONATOLOGÍA", "UNIDAD CUIDADOS INTERMEDIOS", "HEMODIÁLISIS",
  "USO TRANSITORIO (Guardia, Onco, CA Quirurg)", "MATERNIDAD", "SHOCK ROOM"
];

db.origenes = db.origenes.map(item => {
  if (item.nombre && allAmbos.includes(item.nombre.trim().toUpperCase())) {
    return { ...item, reconocimiento: 'ambos' };
  }
  return item;
});

fs.writeFileSync(path, JSON.stringify(db, null, 2));
console.log('db.json updated successfully');
